### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [cilium/cilium.io#164]
**Google has deprecated Universal Analytics** (UA), in favor of its successor, Google Analytics 4 (GA4). This issue is part of a CNCF-wide effort to upgrade project websites to GA4. For more details about the deprecation and the CNCF migration effort, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks: stages 1 & 2

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-V9SYWYG92Y`**
- [x] Enable GA4 site tag, ideally via [Netlify snippet injection] (leaving the GTM site tag in place), "Google Analytics 4 - only in production", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-V9SYWYG92Y"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-V9SYWYG92Y');
  </script>
  {% endif %}
  ```
- [x] Ensure that the GA4 site tag is receiving events.
- [x] I'm going to assume that the GTM tag is still processing events, since the registration code hasn't been touched. If someone with access to that Analytics account can confirm, that would be appreciated.

### Tasks: followup

- Eventually, the GTM tag will stop working. Either it will need to be upgraded, or simply dropped in favor of the GA4 site tag. #194

### Sites

- **Main site**: this issue is for the main site, [cilium.io](https://cilium.io/), which is currently setup with a Google Tag Manager (GTM) tag, `GTM-M533ZSF`.
- **Docs**: I'll be creating a separate issue for the `docs` subdomain, which is built from [cilium/cilium](https://github.com/cilium/cilium). This docs issue is:
  https://github.com/cilium/cilium/issues/22007

/cc @caniszczyk @nate-double-u

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Hi @tgraf @liquidat @xmulligan: who should I contact to gain access to the **Netlify account** for:

- cilium.io
- docs.cilium.io

I believe that the base account access is via [app.netlify.com/sites/cilium](https://app.netlify.com/sites/cilium). Thanks!

**Comment by xmulligan** [comment]
@chalin I can get you access. What do you need?

**Comment by chalin** [comment]
@xmulligan - I need access to the main site's Netlify account, so you'll need to add me via https://app.netlify.com/sites/cilium/members I believe. I can't recall what level of access I need, but we can start with Collaborator. Thanks!

**Comment by chalin** [comment]
@xmulligan - it seems that these two domains are distinct (and not redirected one to the other):

- [docs.cilium.io](https://docs.cilium.io/)
- [docs-cilium-io.netlify.app](https://docs-cilium-io.netlify.app/)

Is that correct? If so, where is the "official" docs domain being served from?

**Comment by xmulligan** [comment]
Sure, should I use your LF email or is there an alias I should use?

I'm not sure about the docs question. @qmonnet might know though

**Comment by chalin** [comment]
> Sure, should I use your LF email or is there an alias I should use?

I just DM'd you via CNCF Slack. Thanks.

**Comment by chalin** [comment]
@xmulligan @qmonnet - any updates on this, post-offsite? To summarize:

- **Cilium Netlify account access**: can one of you grant me access?
- **Docs have two hosts**: I'd like some insights as to why there seem to be two hosting services active for the docs. For context, see my https://github.com/cilium/cilium.io/issues/164#issuecomment-1303814183 from earlier.

**Comment by qmonnet** [comment]
Sorry I'm currently on leave, deferring to Bill or maybe @michi-covalent

**Comment by xmulligan** [comment]
@chalin sorry for the delay, we didn't want to do the switch while on the offsite in case anything went wrong 😅 

@michi-covalent is working on it now

**Comment by chalin** [comment]
Thanks @xmulligan @michi-covalent -- looking forward to hearing from you.

**Comment by michi-covalent** [comment]
hi @chalin ! 👋 

- Cilium Netlify account access: can one of you grant me access?

we are in the process of migrating https://cilium.io site from a private netlify account to cncf account. i'll let you know when the migration is complete.

- Docs have two hosts: I'd like some insights as to why there seem to be two hosting services active for the docs.

https://docs.cilium.io is currently using [readthedocs](https://readthedocs.org/) to host the production site. we use cncf netlify account for deploy previews. https://docs-cilium-io.netlify.app comes from that. not sure if there is a way to disable *.netlify.app domain.

**Comment by lizrice** [comment]
I think I've done it! I have transferred cilium.io to CNCF Projects 2 (where docs.cilium.io was already) 
<img width="1264" alt="Screenshot 2022-11-16 at 10 14 22" src="https://user-images.githubusercontent.com/458616/202153588-b162fa8c-c705-410e-a873-cafcfbf3d379.png">

**Comment by chalin** [comment]
> https://docs.cilium.io is currently using [readthedocs](https://readthedocs.org/) to host the production site. we use cncf netlify account for deploy previews. https://docs-cilium-io.netlify.app comes from that. not sure if there is a way to disable *.netlify.app domain.

I've created a separate issue to track this, see:

- #195

**Comment by chalin** [comment]
> I think I've done it! I have transferred cilium.io to CNCF Projects 2 (where docs.cilium.io was already) 

@lizrice @qmonnet et al.: Cilium.io needs to **opt out of Google's forced & automatic GA4 migration** (since we've migrated already). For details, see:

- #248
